### ISSUE TITLE
Error after open nvim

### ISSUE THREAD

**Issue by ryannewcomer** [doctorfree/nvim-lazyman#11]
Hi. I just install lazyman in my mint wsl2. Then i install nvchad with lazyman -c. It work perfectly at the start, then it open nvim with the default welcome screen. Then i add export NVIM_APPNAME="lazyman-nvchad". But it still don't work. There is no plugin installed, the uni is still the same. How to fix it?

**Comment by ryannewcomer** [comment]
sorry. is my nvim command not working. i juse reinstall nvim with brew and it is now fixed!! thanks and sorry 🙏

**Comment by doctorfree** [comment]
Glad it was something easy. Let me know how it goes and if you see problems or features you would like. Enjoy!
