### ISSUE TITLE
What is the best way to add plugins?

### ISSUE THREAD

**Issue by JPDucky** [doctorfree/nvim-lazyman#35]
What is the best way to add plugins such that they will be available globally? I don't want to hose anything on accident and didn't see anything specific in the docs

**Comment by doctorfree** [comment]
I'm not sure I understand what you want to do. I do not know how to make a plugin globally available for all Neovim configurations installed on a system. Is that what you are wishing to do?

Or, are you seeking to make a Neovim configuration globally available for all users on a system?

Sorry, I am not able to help, can you clarify?

**Comment by JPDucky** [comment]
Single user system. Let me back up a little bit- so I think i was under the impression when I read the docs that plugins were added globally and they carried over to configs, but that doesn't seem to be the case. 

Currently I am trying to figure out why some of my mappings don't work, I'll let you know what I'm doing wrong there once I figure it out.

**Comment by doctorfree** [comment]
Closing but reopen if you think this is an issue with Lazyman
