### ISSUE TITLE
zsh issue with .nvimbind

### ISSUE THREAD

**Issue by nyaahilism** [doctorfree/nvim-lazyman#54]
For some reason ZSH keeps reading the bind command for the Bash Shell inside of the .nvimbind file

```
/.config/nvim-Lazyman/.nvimsbind:08: command not found: bind
/.config/nvim-Lazyman/.nvimsbind:17: command not found: bind
```

I’ve attempted to solve it on my own but I’m like completely new to all this which is why I want to set up a good NVIM config to help me out on my path to learning how to program…

I love Lazyman btw it’s such an amazing project!
```
 /\_/\
(˶ᵔᵕᵔ˶)
 ━〇〇━❥ Thank you for all that you do★
```

**Comment by doctorfree** [comment]
I also use zsh. Let's see what you're environment tells us. What do the following commands output:

```bash
echo $SHELL
echo $ZSH_VERSION
```

The `.nvimsbind` file uses these to figure out which shell you are running. The test it performs is on:

```bash
$SHELL -c 'echo $ZSH_VERSION'
```

What do those commands output when logged in as the user getting the bind not found errors?

Thanks for the kind words!

**Comment by doctorfree** [comment]
@nyaahilism I ran into this same problem in a Docker container where I installed `Lazyman` and solved it by adding the following line to my `~/.zshrc`:

```sh
export SHELL=/bin/zsh
```

If your login shell is zsh you may be able to do something similar in your `~/.zshrc`, using the appropriate path to `zsh`. You can find the path to `zsh` with a command like `type zsh` or `command -v zsh`.
