### ISSUE TITLE
Failed to install certain modules for Allaman config

### ISSUE THREAD

**Issue by wxguy** [doctorfree/nvim-lazyman#59]
Installed Allaman config and I got the following error:

![Screenshot from 2023-12-28 17-08-53](https://github.com/doctorfree/nvim-lazyman/assets/9054645/371a70fd-a05e-46fc-bf65-aff516be5c15)

The above error message is received even after rebooting nvim multiple times.

**Comment by doctorfree** [comment]
I do not get this error when using the Allaman configuration. It could be he fixed it and you happened to install it when it prior to the fix, I haven't checked his repo yet. I do get a non-fatal warning about not being able to load a user config at `~/.nvim_config.lus` so it appears he is using a configuration file outside the scope of Lazyman. But it comes up cleanly anyway.

Did you install Allaman with Lazyman? A patch is included for this configuration so insstalling it manually will not apply the patch. Did you have to do anything to trigger this error or did it come up when you started the session?

When you install a configuration with Lazyman you are getting whatever is currently in that repository and bugs come and go as the authors introduce and subsequently fix them. Or it could be differences between our runtime environments.

Try uninstalling Allaman and reinstalling to see if you just picked up a broken config that was later fixed. If the error persists I will dig deeper.

**Comment by doctorfree** [comment]
I found in some cases I needed to perform a 2nd sync on the `Allaman` configuration. I believe it was timing out sometimes but not always. `Lazyman` has been updated to sync `Allaman` twice. Update with `lazyman -U` and `Allaman` should install and initialize correctly. Reopen this issue if you encounter any problem.
