### ISSUE TITLE
Suggestion: add vimacs to available versions

### ISSUE THREAD

**Issue by rdataforge** [doctorfree/nvim-lazyman#61]
Great work. Now I can test many neovim versions. But I noticed (or I couldn’t find) one of my favourites:
https://github.com/orhnk/vimacs

Thanks!

**Comment by doctorfree** [comment]
Thanks. Yes, Vimacs is an excellent NvChad custom config. However, it has dependencies Lazyman does not satisfy and the initialization process is interactive so it is not officially supported yet in Lazyman. However, you can install and initialize Vimacs using Lazyman with the following command:

```bash
lazyman -V https://github.com/UTFeight/vimacs -o -D custom -N nvim-Vimacs
```

The Cody dependency is not met and there is an interactive portion of thee Vimacs initialization that prompts for Cody. The initialization hangs at this point (for me) and times out after a couple of minutes. Vimacs then comes up clean but with missing dependencies. Give it a shot and let me know how it goes. Supporting Neovim configurations that require interaction during initialization is not yet a feature of Lazyman.

**Comment by rdataforge** [comment]
ok. So maybe I could install Vimacs into nvim-Vimacs and then the command `nvims` could detect it and offer it as option?
I tried it but the command `nvims` always opens lazyman version. No other option is shown (same as neovides command BTW)

**Comment by doctorfree** [comment]
@rdataforge if you install Vimacs using Lazyman with `lazyman -V https://github.com/UTFeight/vimacs -o -D custom -N nvim-Vimacs` then the `nvims` shell function should detect it and present it as an option to open. If it does not then that is a problem and we should open an issue. It works for me.

If you manually install a Neovim configuration, not using the `lazyman` command, then `nvims` doesn't know anything about that. It may be possible to manually install and add an entry to `~/.config/nvim-Lazyman/.nvimdirs`. This will fool Lazyman into thinking it installed the config and `nvims` should then recognize it. This is not a supported solution but you can try it. For example, if you have Vimacs installed in `~/.config/nvim-Vimacs` then try adding a line `nvim-Vimacs` to `~/.config/nvim-Lazyman/.nvimdirs`.

Or, just install it with lazyman. Does that make sense?

**Comment by verajosemanuel** [comment]
installing it with lazyman command worked like a charm. thanks a lot

**Comment by doctorfree** [comment]
Cool. Let me know if you figure out how we can better integrate Vimacs in to Lazyman.
