### ISSUE TITLE
Issues in updating plugins and plugin install problem

### ISSUE THREAD

**Issue by wxguy** [doctorfree/nvim-lazyman#68]
Came to let you know that recently, I encountered an issue in installing lazyman and updating plugins using Lazy. 

The first issue is that lazyman did not install properly.  After installing, whenever I open lman, I get `fzf extension doesn't exist` error. Digging the issue further, I have realised that the `elescope-fzf-native.nvim` didn't install properly. The following commands solved the issue:-

```
cd ~/.local/share/nvim-Lazyman/lazy/telescope-fzf-native.nvim
make
```

The second issue I encountered was while updating all plugins through Lazy. I always got `could not resolve host github.com`. The issue was nothing to do with lazyman. This was DNS resolution issue. I changed from default DNS address to google with following:-

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

in the `/etc/resolv.conf` file.

The OS I am using is RHEL 8.x. Hope it is somebody.

**Comment by doctorfree** [comment]
Thanks for the report. It's possible your DNS issue adversely affected the initial installation of Lazyman. Did you install Lazyman prior to changing your DNS nameservers? If so, I would suggest uninstalling Lazyman and reinstalling now that DNS is working. If not then I will have to think harder.

To uninstall/reinstall Lazyman:

```bash
# This removes any configs previously installed with Lazyman
lazyman -R -A -y
# This uninstalls Lazyman itself
lazyman -R -N Lazyman
# Clone the Lazyman repository
git clone https://github.com/doctorfree/nvim-lazyman $HOME/.config/nvim-Lazyman
# Initialize Lazyman
$HOME/.config/nvim-Lazyman/lazyman.sh
```

The Telescope `fzf-native` plugin performs a `make` following the documentation at the plugin repo's readme. It should get built during initialization if `make` and `gcc` are available on your system. I do not know why it did not get built earlier other than DNS not resolving github.com probably screwed up a lot of stuff.

**Comment by wxguy** [comment]
> ```shell
> ```shell
> $HOME/.config/nvim-Lazyman/lazyman.sh
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

I can confirm that it works now. The main issue was DNS resolution.
