### ISSUE TITLE
lazyman does not work if bob is not present

### ISSUE THREAD

**Issue by verajosemanuel** [doctorfree/nvim-lazyman#69]
Tried installing Lazyman with an existing Nvim previously configured to my liking i want to preserve.
 I cloned the repository and executed:

`$HOME/.config/nvim-Lazyman/lazyman.sh -Z`

Seems to be installed ok but then when executing lazyman:

`The used file required for bob could not be found. This could mean that Neovim is not installed through bob`

system is WSL2 ubuntu.
I do not use bob as i just stick to latest stable version. is there any way to overcome this requirement?

regards

**Comment by doctorfree** [comment]
@verajosemanuel  Thanks for the report. That message is coming from Bob.

Can you check if Bob is installed and remove it if so?

I will check on my end to see how and why Bob would get installed when initializing with `-Z`.

**Comment by verajosemanuel** [comment]
that did the trick. Bob was installed but unused. Thanks

**Comment by verajosemanuel** [comment]
removing bob lead to the same error. Seems that lazyman needs it somewhere. https://github.com/doctorfree/nvim-lazyman/issues/70
