### ISSUE TITLE
bob is required to install lazyman no matter how you install neovim

### ISSUE THREAD

**Issue by verajosemanuel** [doctorfree/nvim-lazyman#70]
related to this issue: https://github.com/doctorfree/nvim-lazyman/issues/69

i have removed bob and installed lazyman but an error persists at the end:

`ERROR Error: The used file required for bob could not be found. This could mean that Neovim is not installed through bob.`

Seems that bob is a hard requirement somewhere

**Comment by doctorfree** [comment]
This message comes from `bob`. It would seem it was not removed. Lazyman does not, by default, install or rely upon `bob`. Check the various locations `bob` is installed:

```bash
ls ~/.cargo/bin/bob
ls `/.local/share/bob
ls /opt/homebrew/bin/bob
```

I will double check and attempt to reproduce this issue. Can you confirm for me the following:

- You previously installed Neovim and a Neovim configuration in `~/.config/nvim/`
-  You installed Lazyman with `~/.config/nvim-Lazyman/lazyman.sh -Z`

**Comment by verajosemanuel** [comment]
yes, i confirm neovim is installed and configured at ~/.config/nvim/  and lazyman is installed with the command provided.
Removed any file from the mentioned paths (only the second existed )  and now i am nable of installing lazyman . Thanks

**Comment by doctorfree** [comment]
Yes, `Bob` removal is a manual process. Glad you were able to remove it and get `Lazyman` working. Perhaps i will add a `Bob` removal option to `Lazyman` or check if `Bob` exits with error and work around that.
