### ISSUE TITLE
Use TMPDIR env vars

### ISSUE THREAD

**Issue by luisdavim** [doctorfree/nvim-lazyman#73]
On some systems, like on termux, for example, `/tmp` is not available, using `$TMPDIR` or `$TEMPDIR` and defaulting to `/tmp` only if neither is set would be better.

**Comment by doctorfree** [comment]
Good suggestion. I pushed changes using `TMPDIR` or `TEMPDIR` or `/tmp` if neither is set. This needs to go through testing before a new release is created but if you have Lazyman installed then `lazyman -U` should pick these changes up. If you do not have `Lazyman` installed then installing from a cloned repository will pickup these changes:

```bash
git clone https://github.com/doctorfree/nvim-lazyman $HOME/.config/nvim-Lazyman
$HOME/.config/nvim-Lazyman/lazyman.sh
```

**Comment by luisdavim** [comment]
Awesome, thanks. I'll give it a try.

**Comment by luisdavim** [comment]
Gave it a try and it seems to be working as expected.  Thanks.
