### ISSUE TITLE
How to pick up after a failed install?

### ISSUE THREAD

**Issue by bedge** [doctorfree/nvim-lazyman#74]
My company uses self signed certs as part of their VPN setup. 
This caused some items to fail during the initial run:
```
        Installing nvm node version manager ... done
        Verifying latest version of node with nvm ... done
        Verifying latest version of npm with nvm ... done
Installing language servers and tools
        Installing ccls ... done
        Installing cargo ...curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
....
        Installing misspell ...curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html


curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
 done
Installing Ruby dependencies
        Installing ruby-dev ... done
        Installing Ruby neovim gem ... done
        Installing deno ... done
        Installing tectonic ...curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html
```

When I re-ran the `$HOME/.config/nvim-Lazyman/lazyman.sh` script it doesn't retry any of the failed items.

I resorted to dropping the VPN deleting all of the installed components and re-running, but ideally the install script would be more idempotent and install only what failed on previous executions.

I believe that one could also work around this using `curl --insecure`. Perhaps provide that as an option for those in a similar situation?

Thanks

**Comment by doctorfree** [comment]
Thanks for opening an issue on this @bedge 

I've updated `Lazyman` to permit insecure downloads with `curl`. This is still under testing and will be in the next release when qualified. You can try it out now by updating `Lazyman` with the command `lazyman -U` and reinstall missing language servers and tools with `lazyman -I`

If you encounter errors after updating and reinstalling tools then update this issue and we will tackle them.

**Comment by bedge** [comment]
That's fantastic, thank you. I will retry now.

BTW, I'm testing this on WSL. I spent a ton of time researching into which vim framework I wanted, only then to realize it wasn't windows compatible. 
No matter, I will try something like https://github.com/doctorfree/nvim-lazyman/issues/71

Another thought, while I'm at it - a docker target? 
I suppose that's what I'm doing in WSL, but it's part of my WSL instance. I was thinking that a stand-alone would be great as then, one could be truly OS independent and perhaps even simplify some of the variant logic. (Although, other fans with dedicated OS prefs will curse me for even suggesting their favorite platform get dropped).

Anyway. retrying now. Thanks! Will report back.

**Comment by bedge** [comment]
Follow-up - 

The -U option hung up.
```
❯ $HOME/.config/nvim-Lazyman/lazyman.sh -U

Updating existing nvim-Lazyman config at /home/edgeb1/.config/nvim-Lazyman
Saving new configuration file as:
        /home/edgeb1/.config/nvim-Lazyman/lua/configuration-new.lua
Restoring your previous configuration file as:
        /home/edgeb1/.config/nvim-Lazyman/lua/configuration.lua

```

Here's the process tree:

![image](https://github.com/user-attachments/assets/4c71c083-47d4-4e81-aa53-bb053c86a174)


This is probably my fault as I didn't actually re-read your update, but remembered something about a `-I` option, so I re-cloned and ran that....

Ran to completion, no errors.

Then I re-read and noticed the `-U` and thought, OK, needed to run that 1st. (not thinking that the reclone sort of bypassed that whole thing).

Anyway. this is just an FYI at this point, as my behavior I (-I then -U, makes zero sense).

Feel free to close.

**Comment by bedge** [comment]
All issues resolved. The above hang up is no longer of any interest.
